# Format, Version: Tool File
%IMPERIAL, 7.0 X0
#
# Author: GerbTool for Windows 7.0 X0 (c) 1992-1995 WISE Software Solutions, Inc.
# Date:   Tue Oct 15 13:27:59 1996
#
# Tool #    Size     Feed  Dcode
#
    1      0.0200      0    14
    2      0.0300      0    16
    3      0.0400      0    18
    4      0.0600      0    20
    5      0.0800      0    24
    6      0.1000      0    28
